server:
    port: ${PORT:8081}

spring:
    application:
        name: produtos
    datasource:
        driverClassName: org.postgresql.Driver
        url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/db_produtos}
        username: ${DATASOURCE_USERNAME:postgres}
        password: ${DATASOURCE_PASSWORD:teste123}
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update  # Use 'update' to automatically update schema (create or update tables)
        properties:
            hibernate:
                jdbc:
                    time_zone: UTC  # Set JDBC time zone to UTC (optional, adjust as needed)
        show-sql: false  # Enable SQL logging (optional, for debugging)
        generate-ddl: false  # Generate DDL from entity models (optional, for schema creation)
        open-in-view: false  # Disable Open Session in View (OSIV) to prevent lazy loading issues

    mvc:
        format:
            date: yyyy-MM-dd
            date-time: yyyy-MM-dd HH:mm:ss
            time: HH:mm:ss

    security:
       oauth2:
          resourceserver:
             jwt:
                issuer-uri: http://localhost:9000
                jwk-set-uri: http://localhost:9000/oauth2/jwks 

logging:
    level:
        org.springframework.security: TRACE
